[package]
name = "aoc2022"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
bit-set = "0.5"
itertools = "0.10"
maplit = "1"
regex = "1"
serde_json = "1"

[profile.release]
panic = "abort"
lto = true
